graph_directory: /Users/lizcconrad/Documents/PhD/POGG/POGG_project/POGG_data/development/Tutorial/subgraphs/dot/complete
results_directory: /Users/lizcconrad/Documents/PhD/POGG/POGG_project/POGG_data/development/Tutorial/results
LEXICON: /Users/lizcconrad/Documents/PhD/POGG/POGG_project/POGG_data/development/Tutorial/Tutorial_lexicon.json