graph_directory: /Users/lizcconrad/Documents/PhD/POGG/POGG_project/POGG_data/synthesized/ling575_presentation/graphs
results_directory: /Users/lizcconrad/Documents/PhD/POGG/POGG_project/POGG_data/synthesized/ling575_presentation/results
LEXICON: /Users/lizcconrad/Documents/PhD/POGG/POGG_project/POGG_data/synthesized/ling575_presentation/lexicon.json