graph_directory: /Users/lizcconrad/Documents/PhD/POGG/POGG_project/POGG_data/synthesized/micrograph
results_directory: /Users/lizcconrad/Documents/PhD/POGG/POGG_project/POGG_data/synthesized/micrograph/results
LEXICON: /Users/lizcconrad/Documents/PhD/POGG/POGG_project/POGG_data/synthesized/micrograph/lexicon.json