graph_directory: /Users/lizcconrad/Documents/PhD/POGG/POGG_project/POGG_data/development/Heal_TheCar/subgraphs/dot/complete
results_directory: /Users/lizcconrad/Documents/PhD/POGG/POGG_project/POGG_data/development/Heal_TheCar/results
LEXICON: /Users/lizcconrad/Documents/PhD/POGG/POGG_project/POGG_data/development/Heal_TheCar/Heal_TheCar_lexicon.json