graph_directory: /Users/lizcconrad/Documents/PhD/POGG/POGG_project/POGG_data/synthesized/bitsy_bakery
results_directory: /Users/lizcconrad/Documents/PhD/POGG/POGG_project/POGG_data/synthesized/bitsy_bakery/results
LEXICON: /Users/lizcconrad/Documents/PhD/POGG/POGG_project/POGG_data/synthesized/bitsy_bakery/lexicon.json